### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shakeyourbunny** [ali1234/ytsubs#5]
Starting this script with the environment-set API key yields:

```
$ python ytsubs.py myyoutubeuser
Traceback (most recent call last):
  File "ytsubs.py", line 119, in <module>
    playlists = get_playlists(get_channel_for_user(username))
  File "ytsubs.py", line 50, in get_channel_for_user
    return data['items'][0]['id']
IndexError: list index out of range
```

I do provide my correct youtube user, what I'm doing wrong?

python version is 2.7.10rc1

**Comment by ali1234** [comment]
Not sure. Maybe you are subscribed to someone who has no videos?

**Comment by imbolc** [comment]
I have the same problem. I tried different accounts. The answer form server is: {u'items': [], u'kind': u'youtube#channelListResponse', u'etag': u'"..."', u'pageInfo': {u'resultsPerPage': 5, u'totalResults': 0}}

**Comment by jldowns** [comment]
Youtube accounts created recently don't have usernames, they have "user id"s. (Your username is *not* your email address.) I changed line 46 to
```
url = baseurl + '/channels?part=id&id='+ user + '&key=' + my_key
```
and ran the program using 
```
YOUTUBE_SERVER_API_KEY="<your_secret_key>" ./ytsubs.py <channel_id> <output RSS file>
```

and everything worked. You can find your channel id in Youtube Account Settings > Overview > Name > Advanced
